spring:
  application:
    name: Accounts Payable API
  datasource:
    url: jdbc:postgresql://db:5432/contasdb
    username: contasuser
    password: contaspwd
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
